# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c3c0c559a944735300426e73f32944e8674f1a2b545b26abbabf67d7f3fef1c5cef1445b5ca68e1bca0f8e013cb3c39b08a679c2c2c79d73509bf2cad3edb78

test:
  secret_key_base: 0de6e67c2d87c8bb308aa33ed57102f3bf4b376c6cc2549902e4212670cc4c413bac6ef673dae65a437383d6c09789aaf4670a9e4ca95a237bcc9e5e9ff161ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
